[title]
type = 0
optional = false
[title.string]
length = 75
# pattern
# enum/whitelist
# blacklist
# [title.int]
# start
# stop
# step
# [title.array]
# [title.ojbect]


[priority]
type = 1
optional = true
[priority.valid]
start = 0
end = 10
